#!/bin/sh
### BEGIN INIT INFO
# Provides:          start-udhcpd
# Required-Start:    
# Default-Start:     S
# Default-Stop:      0 6
### END INIT INFO

case "$1" in
    start)
        echo "Starting UDHCPD server..."
        udhcpd -f /etc/udhcpd.conf &
        ;;
    stop)
        echo "Stopping UDHCPD server..."
        killall udhcpd
        ;;
    restart)
	echo "Restarting UDHCPD server..."
        $0 stop
        sleep 2
        $0 start
        ;;
    *)
        echo "Uso: $0 {start|stop|restart}"
        exit 1
esac

exit 0

